use_frameworks!

target 'SKImageExtension_Example' do
  pod 'SKImageExtension', :path => '../'

  target 'SKImageExtension_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
